[package]
name = "emoji-crafter"
description = "a command line tool for automating emoji exports from svg, including animation"
license-file = "license.md"
version = "0.0.0"
edition = "2018"

[dependencies]
gif = "0.11"
resvg = "0.17"
rayon = "1.5"
serde = { version = "1.0", features = ["derive"] }
tiny-skia = "0.6"
toml = "0.5"
usvg = "0.17"
webp-animation = "0.2"
xmltree = "0.10"
